name: Sync to Google Drive

on:
  push:
    branches:
      - main # 본인 저장소의 기본 브랜치명이 master라면 master로 변경
    paths:
      - 'source' # 깃허브에 올라가 있는 소스코드 파일의 정확한 이름 (확장자가 있다면 source.js 형태로 수정)

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload File to Google Drive
        uses: adityak74/google-drive-upload-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: "source" # 구글 드라이브에 업로드할 대상 파일명
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true" # 기존 파일에 덮어쓰기 활성화
